{
 "title": "PVZ Service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "📊 Кол-во запросов (в минуту)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=\"pvz-service:9000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏱ Среднее время ответа (мс)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_duration_seconds_sum{job=\"pvz_service\"}[1m])) / sum(rate(http_response_duration_seconds_count{job=\"pvz_service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏪 Количество ПВЗ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvz_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "📦 Количество приемок",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "receptions_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🛒 Количество товаров",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "products_added_total", "legendFormat": "__auto" }
   ]
  }
 ]
}